import os


API_TOKEN = os.environ["TELEGRAM_API_TOKEN"]
TENBIS_OFFICE_LOCATION = os.environ["TENBIS_OFFICE_LOCATION"]
WEBHOOK_HOST = os.environ["WEBHOOK_HOST"]
WEBHOOK_PORT = int(os.environ["WEBHOOK_PORT"])

WEBHOOK_LISTEN = '0.0.0.0'

WEBHOOK_SSL_CERT = './webhook_cert.pem'
WEBHOOK_SSL_PRIV = './webhook_pkey.pem'

WEBHOOK_URL_BASE = f"https://{WEBHOOK_HOST}:{WEBHOOK_PORT}"
WEBHOOK_URL_PATH = f"/{API_TOKEN}"



