import os


API_TOKEN = os.environ["TELEGRAM_API_TOKEN"]
TENBIS_OFFICE_LOCATION = os.environ["TENBIS_OFFICE_LOCATION"]
WEBHOOK_HOST = os.environ["WEBHOOK_HOST"]
WEBHOOK_PORT = int(os.environ.get("PORT", "8443"))

WEBHOOK_LISTEN = '0.0.0.0'

WEBHOOK_URL_BASE = f"https://{WEBHOOK_HOST}:{WEBHOOK_PORT}"
WEBHOOK_URL_PATH = f"/{API_TOKEN}"



